add meetup-001-report
typescript-jp/typescript-jp.dev pull request #4
Opened 2019-06-27 14:44 UTC by sasurau4

## Overview
add TypeScript Meetup #1 Report

2019-06-28 00:58 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +I'll let you know about TypeScript Meetup Japan and introduce the simple summary of each talks.
[Question] each って後ろに複数形取れましたっけ

2019-06-28 00:59 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +- Someone who has TypeScript knowladge hesitate to talk about TypeScript specific topic in JavaScript meetup.
```suggestion
- Someone who has TypeScript knowledge hesitate to talk about TypeScript specific topic in JavaScript meetup.
```

2019-06-28 01:02 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +The organizer leko talk about why TypeScript meetup held and the purpuse of TypeScript Meetup Japan.
```suggestion
The organizer leko talked about why TypeScript meetup is held and the purpose of TypeScript Meetup Japan.
```

2019-06-28 01:03 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +The organizer leko talk about why TypeScript meetup held and the purpuse of TypeScript Meetup Japan.
is ? was ?

2019-06-28 01:05 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +At last, he told about his thought to remove barriars of types by this talk.
```suggestion
At last, he told about his thought to remove barriers of types by this talk. 
```

2019-06-28 01:06 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +She talked about about the long effort of modernizing pixiv with TypeScript.
```suggestion
She talked about the long effort of modernizing pixiv with TypeScript.
```

2019-06-28 01:10 UTC, fsubal commented on content/blog/meetup-001-report/index.md
> +At last, we thanks to the Microsoft Japan's staff who helped us, all the speakers and all attendees. Of cource also thank for the awesome Language TypeScript and TypeScript core team members!
```suggestion
At last, we thanks to the Microsoft Japan's staffs who helped us, all the speakers and all attendees. Of course also thank for the awesome Language TypeScript and TypeScript core team members!
```

2019-06-28 14:42 UTC, sasurau4 commented on content/blog/meetup-001-report/index.md
> +I'll let you know about TypeScript Meetup Japan and introduce the simple summary of each talks.
取れませんでした :scream: 
>  every one of two or more things or people, considered separately
https://www.ldoceonline.com/jp/dictionary/each
https://www.b-cafe.net/newsletter/2012/06/003166.php

2019-06-28 14:43 UTC, sasurau4 commented on content/blog/meetup-001-report/index.md
> +I'll let you know about TypeScript Meetup Japan and introduce the simple summary of each talks.
```suggestion
I'll let you know about TypeScript Meetup Japan and introduce the simple summary of each talk.  
```

2019-06-30 01:59 UTC, Leko commented on content/blog/meetup-001-report/index.md
> +### Opening Talk
オープニングトークで特に記録するようなことはなかったと思うので要らないと思う

2019-06-30 01:59 UTC, Leko commented on content/blog/meetup-001-report/index.md
> +Mr.Leko[leko's twitter] started planning TypeScript Meetup to solve these problems from Mar 23th, 2019. We, the staffs, got together and lauched the community TypeScript Meetup Japan to prepare the p
> leko's twitter

https://twitter.com/L_e_k_o

2019-06-30 01:59 UTC, Leko commented on content/blog/meetup-001-report/index.md
> +In Tokyo, Japan, there are a lot of meetups about various JavaScript topics. For example [Gontanda.js](https://gotanda.js.org/), [Meguro.es](https://meguro.es/), [Angular Japan / Tokyo](https://www.m
こんなに例示いるかな？ちょっと多いかなと思いました
React, Vue, Angularのコミュニティや、ご当地ローカルなJavaScriptコミュニティがたくさんあります、しかしJSなのでTSの話はしにくいのじゃ
的な感じでいいんじゃないかなと

2019-06-30 01:59 UTC, Leko commented on content/blog/meetup-001-report/index.md
> +- Speaker: Shingo Inouse aka [Leko](https://twitter.com/L_e_k_o)
Lekoの方だけ書いておいてほしい

2019-07-02 03:37 UTC, sasurau4 commented
@Leko @fsubal fix pointed out!

2019-07-02 03:44 UTC, Leko requested changes

2019-07-02 03:44 UTC, Leko commented on content/blog/meetup-001-report/index.md
> +title: TypeScript Meetup \#1 Report
:eyes:

2019-07-02 07:15 UTC, Leko approved these changes

2019-07-02 07:15 UTC, merged